backend:
  name: github
  branch: main 
  repo: niwee-productions/docs

media_folder: "static/icons" # Media files will be stored in the repo under static/images/uploads
public_folder: "/icons/"

collections:
- name: docs
  label: "Index"
  folder: docs
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: intro
  label: "Introduction"
  folder: docs/intro
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: nwservers
  label: "NW Servers"
  folder: docs/nw-servers
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: cloudpanel
  label: "Cloudpanel"
  folder: docs/cloudpanel
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: cli
  label: "NiWee CLI"
  folder: docs/cli
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: clicommands
  label: "CLI Commands"
  folder: docs/cli/commands
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: cicd
  label: "CI/CD"
  folder: docs/ci-cd
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }

- name: wordpress
  label: "Wordpress"
  folder: docs/wordpress
  identifier_field: title
  extension: md
  format: frontmatter
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - { name: sidebar_label, label: Sidebar Label, widget: string }
    - { name: hide_table_of_contents, label: Hide Table of Contents, widget: boolean, default: false, required: false }