name: SSH CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/htdocs/${{ secrets.URI }}
          git fetch --all
          git reset --hard origin/main
          git clean -df
          git pull origin main
          yarn install
          yarn build